### ISSUE TITLE
Using `composes` twice with the same file leads to it beeing included twice

### ISSUE THREAD

**Issue by mhsdesign** [g45t345rt/esbuild-style-plugin#16]
There is a postcss modules feature called `composes` which allows to reuse a css class.

it can be used like this:

mixin.module.css
```css
.mixin {
    background: violet;
}
```

button.module.css
```css
.button {
    composes: mixin from './mixin.module.css';
    color: blue;
}
```

this should result in the exported class `button` beeing mapped to both  `.button` and `.mixin`
```js
var button_module_default = {
  "button": "_button_bw4zf_2 _mixin_14j59_2"
};
```

and this works well.

but if we use `composes: mixin from './mixin.module.css';` multiple times, we will also include the mixin multiple times.

Not only does this hurt bundle size - its also causes css-specifity issues.

i made an example repo:
https://github.com/mhsdesign/esbuild-style-plugin-composes
 
the bundled css looks like this: but i would expect only the first `_mixin_1gyx8_2` to be present for the correct css order.
```css
/* temp_stylePlugin:ni:sha-256;teeu0O0SBgTYRVosihvCNUPbWqQhltpKpAaYrDOLAmw */
._mixin_1gyx8_2 {
  background: lightgray;
  border: 1px solid black;
  margin: 1rem;
  padding: 1rem;
}
._button_bw4zf_2 {
  color: blue;
}

/* temp_stylePlugin:ni:sha-256;VZaVzVr8w94ejytTy_ZMqISjo2RsjxEDpifxtYEDMeA */
/* this should not be included twice */
._mixin_1gyx8_2 {
  background: lightgray;
  border: 1px solid black;
  margin: 1rem;
  padding: 1rem;
}
._text_tiv5k_2 {
  color: green;
}
```
got:
![image](https://user-images.githubusercontent.com/85400359/197171178-7ecbf725-2e2a-4f81-88b2-84d7875a2963.png)

expected:
![image](https://user-images.githubusercontent.com/85400359/197171272-c26c1886-cc59-4c7b-a4cd-28476a85c7cd.png)
